<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
شکلات‌های خوب‌تر
</font>
</h1>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
فرض کنید که بعد از میل کردن چند شکلات معمولی (غیر دارک) متوجه شده‌ایم که بسیاری از آن‌ها هم خوشمزه هستند و اگر بتوانیم موارد با کیفیت‌تر آن‌ها را پیدا کنیم احتمالاً فروش خوبی خواهند داشت. پس در گام آخر از پروژه می‌خواهیم شرکت‌هایی که شکلات‌های باکیفیت‌تری را تولید می‌کنند شناسایی کرده و شکلات‌های ‌‌آن‌ها را جدا کنیم.
</font>
</p>


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در گام پیشین قیمت شکلات‌ها را تخمین زده و دیتافریم نهایی را در فایلی به نام <code>chocolate_price.csv</code> ذخیره کردید. در ابتدا آن فایل را به شکل یک دیتافریم بخوانید.
</font>
</p>


In [114]:
import numpy as np
import pandas as pd

df = pd.read_csv('chocolate_price.csv')
df.head()

Company Specific Bean Origin  Review Date  Cocoa Percent Company Location  \
0  A. Morin          Agua Grande         2016           63.0           France   
1  A. Morin                Kpime         2015           70.0           France   
2  A. Morin               Atsane         2015           70.0           France   
3  A. Morin                Akata         2015           70.0           France   
4  A. Morin               Quilla         2015           70.0           France   

   Rating Bean Type Broad Bean Origin  price(100g)  
0    75.0     Blend          Sao Tome     118125.0  
1    55.0     Blend              Togo      96250.0  
2    60.0     Blend              Togo     105000.0  
3    70.0     Blend              Togo     122500.0  
4    70.0     Blend              Peru     122500.0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت اول
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
توجه داشته باشید که در این گام تنها با شکلات‌های غیرتلخ کار داریم. پس در ابتدا تنها شکلات‌هایی که درصد کاکائوی آن‌ها کمتر یا مساوی  ۷۰ درصد است را جدا کرده و در دیتافریم <code>df</code> ذخیره کنید.
</font>
</p>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<span style="color:green"><b>راهنمایی:</b></span>
بعد از جداسازی و ساخت دیتافریم، به کمک تابع <code dir=ltr>reset_index()</code> نمایه‌ها را ریست کنید. در این مرحله به آرگومان‌های <code>inplace</code> و <code>drop</code> هم توجه کنید.
</font>
</p>

In [115]:
df = df[df['Cocoa Percent'] <= 70]
df.reset_index(drop=True, inplace=True)
df

Company Specific Bean Origin  Review Date  Cocoa Percent  \
0    A. Morin          Agua Grande         2016           63.0   
1    A. Morin                Kpime         2015           70.0   
2    A. Morin               Atsane         2015           70.0   
3    A. Morin                Akata         2015           70.0   
4    A. Morin               Quilla         2015           70.0   
..        ...                  ...          ...            ...   
995    Zotter                 Peru         2011           70.0   
996    Zotter                Congo         2011           65.0   
997    Zotter         Kerala State         2011           65.0   
998    Zotter         Kerala State         2011           62.0   
999    Zotter   Brazil, Mitzi Blue         2010           65.0   

    Company Location  Rating  Bean Type Broad Bean Origin  price(100g)  
0             France    75.0      Blend          Sao Tome     118125.0  
1             France    55.0      Blend              Togo      96250.0  
2             France    60.0      Blend              Togo     105000.0  
3             France    70.0      Blend              Togo     122500.0  
4             France    70.0      Blend              Peru     122500.0  
..               ...     ...        ...               ...          ...  
995          Austria    75.0      Blend              Peru     131250.0  
996          Austria    60.0  Forastero             Congo      97500.0  
997          Austria    70.0  Forastero             India     113750.0  
998          Austria    65.0      Blend             India     100750.0  
999          Austria    60.0      Blend            Brazil      97500.0  

[1000 rows x 9 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت دوم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در این قسمت به ازای هر شرکت شکلات‌سازی، میانگین امتیاز شکلات‌های آن را برای هر سال محاسبه کرده و همچون جدول زیر در دیتافریم <code>companies</code> ذخیره کنید.

<center>

| | 2006 | ... | 2015 | 2016 | 2017 |
| :---: | :---: | :---: | :---: | :---: | :---: |
| A. Morin | NaN | ... | 63.75 | 75.0 | NaN |
| ... | ... | ... | ... | ... | ...  |
| hexx | NaN | ... | 60.00 | NaN | NaN |
| twenty-four blackbirds | NaN | ... | NaN | NaN | NaN |

</center>
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<span style="color:green"><b>راهنمایی:</b></span>
بعد از استفاده از دستور <code>groupby</code> و محاسبه‌ی میانگین از دستور <code>unstack</code> استفاده کنید.
</font>
</p>

In [116]:
companies = df.groupby(['Company','Review Date'])['Rating'].mean().unstack()
companies

Review Date             2006  2007  2008  2009  2010  2011       2012  \
Company                                                                 
A. Morin                 NaN   NaN   NaN   NaN   NaN   NaN  72.500000   
AMMA                     NaN   NaN   NaN   NaN  77.5   NaN        NaN   
Acalli                   NaN   NaN   NaN   NaN   NaN   NaN        NaN   
Adi                      NaN   NaN   NaN   NaN   NaN  55.0        NaN   
Aequare (Gianduja)       NaN   NaN   NaN  57.5   NaN   NaN        NaN   
...                      ...   ...   ...   ...   ...   ...        ...   
Zokoko                   NaN   NaN   NaN   NaN   NaN  70.0        NaN   
Zotter                   NaN   NaN   NaN   NaN  60.0  67.5  69.285714   
hello cocoa              NaN   NaN   NaN   NaN   NaN   NaN        NaN   
hexx                     NaN   NaN   NaN   NaN   NaN   NaN        NaN   
twenty-four blackbirds   NaN   NaN   NaN   NaN   NaN   NaN        NaN   

Review Date                  2013  2014   2015  2016  2017  
Company                                                     
A. Morin                66.363636  70.0  63.75  75.0   NaN  
AMMA                          NaN   NaN    NaN   NaN   NaN  
Acalli                        NaN   NaN  75.00   NaN   NaN  
Adi                           NaN   NaN    NaN   NaN   NaN  
Aequare (Gianduja)            NaN   NaN    NaN   NaN   NaN  
...                           ...   ...    ...   ...   ...  
Zokoko                        NaN   NaN    NaN  65.0   NaN  
Zotter                        NaN   NaN    NaN   NaN   NaN  
hello cocoa                   NaN   NaN  55.00   NaN   NaN  
hexx                          NaN   NaN  60.00   NaN   NaN  
twenty-four blackbirds  65.000000   NaN    NaN   NaN   NaN  

[313 rows x 12 columns]

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
خطوط زیر برای استانداردسازی شکل جدول اعمال می‌شوند. این خطوط را تغییر نداده و تنها سلول زیر را اجرا کنید.
</font>
</p>

In [117]:
companies.columns.name = None
companies.index.name = None

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت سوم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
برای پیدا کردن بهترین شرکت‌ها می‌خواهیم تنها امتیاز سال‌های ۲۰۱۲ به بعد را در نظر بگیریم (خود سال ۲۰۱۲ را هم در نظر بگیرید).
ابتدا به ازای هر کمپانی، میانگین امتیاز سال‌های ۲۰۱۲ به بعد آن را محاسبه کرده و در متغیر <code>mean_ratings</code> ذخیره کنید.
توجه داشته باشید که خروجی شما باید یک سری پانداز (<code>pd.Series</code>) باشد.
</font>
</p>


In [118]:
mean_ratings = companies.loc[:, "2012":].apply(lambda row: row.mean(),axis=1)
mean_ratings

A. Morin                  69.522727
AMMA                            NaN
Acalli                    75.000000
Adi                             NaN
Aequare (Gianduja)              NaN
                            ...    
Zokoko                    65.000000
Zotter                    69.285714
hello cocoa               55.000000
hexx                      60.000000
twenty-four blackbirds    65.000000
Length: 313, dtype: float64

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
اکنون به کمک میانگین امتیاز هر کمپانی (<code>mean_ratings</code>)، ۱۰ کمپانی با بهترین امتیاز را پیدا کنید و در متغیر <code>best_ratings</code> ذخیره کنید. توجه داشته باشید که خروجی شما باید یک سری پانداز (<code>pd.Series</code>) باشد.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<span style="color:purple"><b>توجه:</b></span>
در مواردی که امتیاز کمپانی‌ها یکسان باشد، باید کمپانی را براساس ترتیب حروف الفبا انتخاب کنید. به‌عنوان مثال اگر دو کمپانی <code>A</code> و <code>B</code> هر دو میانگین امتیاز <code>75.00</code> داشته باشند، اولویت با شرکت <code>A</code> است.
</font>
</p>

In [119]:
mean_ratings1= mean_ratings.copy()
mean_ratings_df = mean_ratings1.reset_index()
mean_ratings_df.columns = ['Company', 'Mean Rating']
# Sort by 'Mean Rating' in descending order and 'Company' in ascending order
sorted_companies = mean_ratings_df.sort_values(by=['Mean Rating', 'Company'], ascending=[False, True])
# Get top 10 companies
best_ratings = sorted_companies.head(10)
best_ratings.set_index('Company',inplace=True)
best_ratings.index.name = None
best_ratings=best_ratings.squeeze()


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت چهارم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
اکنون شکلات‌هایی که کمپانی سازنده‌شان جزو ۱۰ شرکت برتر (<code>best_ratings</code>) است را از دیتافریم <code>df</code> انتخاب کرده و در دیتافریم <code>chocolates_to_sell</code> ذخیره کنید.
</font>
</p>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<span style="color:green"><b>راهنمایی ۱:</b></span>
بعد از انتخاب این شکلات‌ها، به‌کمک دستور <code>reset_index</code> نمایه‌ها را ریست کنید. استفاده از آرگومان <code>drop</code> را نیز فراموش نکنید.

<br>
<span style="color:green"><b>راهنمایی ۲:</b></span>
برای بررسی وجود یک متغیر در یک لیست می‌توانید از تابع <code>isin</code> استفاده کنید.
</font>
</p>

In [121]:
chocolates_to_sell = None # To-Do

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت پنجم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در نهایت مجموع قیمت این شکلات‌ها (<code>chocolates_to_sell</code>) را در متغیر <code>priceSum</code> ذخیره کنید تا مجموع دریافتی ما از این شکلات‌ها هم مشخص شود.
</font>
</p>

In [122]:
priceSum = None # To-Do